# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosPodExplore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosPodExplore
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'iosPodExploreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosPodExploreUITests' do
    # Pods for testing
  end

end
